# Generated by Django 4.1.4 on 2022-12-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_saloon_db', '0003_alter_saloon_latitude_alter_saloon_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloon',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='saloon',
            name='longitude',
        ),
    ]
