# Generated by Django 4.1.4 on 2022-12-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_saloon_db', '0004_remove_saloon_latitude_remove_saloon_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='saloons',
        ),
    ]
